//Defines for atom layers and planes
//KEEP THESE IN A NICE ASCENDING ORDER, PLEASE

//NEVER HAVE ANYTHING BELOW THIS PLANE ADJUST IF YOU NEED MORE SPACE

#define CLICKCATCHER_PLANE -99
#define LOWEST_EVER_PLANE -200

#define GAME_PLANE -18